### ISSUE TITLE
How can I use the ajax call?

### ISSUE THREAD

**Issue by n1vekk** [creativetimofficial/ct-argon-dashboard-pro-laravel#33] opened 2021-04-08 06:34 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?
using the Laravel+bootstrap version, built passport on laravel and trying to call the api in js file using the $.ajax

# Failure Information (for bugs)
Error message: $.ajax is not a function

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.
It not a bug.
The template uses the jquery slim, but $.ajax is not a slim function.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Laptop
* Operating System: Windows
* Browser and Version: Chrome

## Failure Logs

Please include any relevant log snippets or files here.
![image](https://user-images.githubusercontent.com/29590370/113979507-556dec80-9813-11eb-913b-ea18df74d30e.png)

**Comment by teamupdivision** [comment] 2021-04-15 09:49
Hi @chang4952,

Thank you for reporting this issue and for using Creative Tim products.
 
Could you please send a few more details or a video recording with the steps? It will help a lot in investigating this further. 
 
All the best,
UPDIVSION Team

**Comment by teamupdivision** [comment] 2021-04-28 11:08
Hi @chang4952,

We would like to check if the issue was solved or if you can share a few more details on the steps followed. Please let us know if there is anything else we can help with and if you have any other issues.

Best,
UPDIVISION Team

**Comment by teamupdivision** [comment] 2021-06-09 05:48
Hi @cl4952, 
 
Hope the problem is solved now. We will go ahead and close this ticket. If there is anything else that can be fixed or we can help with, please let us know.

Best,
UPDIVISION Team

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Closed as completed by teamupdivision** 2021-06-09 05:48 UTC
